CREATE TABLE jogos(
nome VARCHAR(100) DEFAULT 'NEYMAR',
quedas SMALLINT);


--AUTOMATICAMENTE O NOME RECEBE NEYMAR POIS NÃO É PASSADO O NOME NO INSERT
INSERT INTO jogos(quedas) VALUES(20);

INSERT INTO jogos(quedas,nome) VALUES(2,'TITE');